"use strict";
const canvas=document.getElementById("screen"),ctx=canvas.getContext("2d",{alpha:false});
const lockText=document.getElementById("lock"),stats=document.getElementById("stats"),message=document.getElementById("message"),levelTitle=document.getElementById("levelTitle");
const IW=240,IH=135,view=document.createElement("canvas");view.width=IW;view.height=IH;const vctx=view.getContext("2d",{alpha:false});vctx.imageSmoothingEnabled=false;
const LEVELS=[
{name:"Level 0 — Yellow Halls",type:"rooms",ceiling:["#9d9568","#c7bc75"],floor:["#706645","#403a2a"],wall:[211,204,129],side:[183,176,105]},
{name:"Level 1 — Concrete Lots",type:"rooms",ceiling:["#666a68","#878b88"],floor:["#505452","#282b2a"],wall:[141,145,141],side:[102,106,103]},
{name:"Level 2 — Pipe-lined Halls",type:"rooms",ceiling:["#716b60","#918677"],floor:["#514a43","#26221f"],wall:[155,145,128],side:[112,103,91]},
{name:"Level 3 — Electricals",type:"rooms",ceiling:["#4f4b45","#6b655c"],floor:["#35322f","#171615"],wall:[116,108,95],side:[77,72,64]},
{name:"Level 4 — Blue Office",type:"rooms",ceiling:["#aab5ba","#cbd5d9"],floor:["#78868b","#4d595e"],wall:[185,203,211],side:[139,159,167]},
{name:"Level 5 — The Hotel",type:"rooms",ceiling:["#5d493c","#8a6b55"],floor:["#5b2527","#2f1113"],wall:[137,105,78],side:[93,67,49]},
{name:"Level 6 — Darkness",type:"rooms",ceiling:["#070707","#111111"],floor:["#080808","#020202"],wall:[44,44,42],side:[28,28,27]},
{name:"Level 7 — The Ocean",type:"rooms",ceiling:["#657782","#9caab0"],floor:["#315d70","#193746"],wall:[151,162,160],side:[105,116,115]},
{name:"Level 8 — Caves",type:"cave",ceiling:["#24211f","#3a3531"],floor:["#282521","#121110"],wall:[87,80,72],side:[57,52,47]},
{name:"Level 9 — Dark Suburbs",type:"suburb",ceiling:["#101723","#202d3e"],floor:["#23282b","#101315"],wall:[76,82,85],side:[48,53,56]},
{name:"Level 10 — The Fields",type:"fields",ceiling:["#89a5bb","#c6d3d8"],floor:["#657c42","#334322"],wall:[135,145,99],side:[90,101,67]}];
const SPR={flashlight:["00022000","00222200","02211220","00222200","00022000","00022000","00033000","00033000"],almond:["00044000","00444400","04455440","04555540","04555540","04455440","00444400","00044000"],battery:["00066000","00666600","06677660","06677660","06677660","06677660","00666600","00066000"],lidar:["00088000","00888800","08899880","08900980","08900980","08899880","00888800","00088000"]};
const COL={1:"#d8e0c8",2:"#6e766d",3:"#30352f",4:"#d5edf6",5:"#6ea6bf",6:"#c9b86e",7:"#6e6236",8:"#79d7c7",9:"#d8fff3"};
let currentLevel=0,titleTimer=0,transitionCooldown=0;const player={x:2.5,y:2.5,angle:0,fov:Math.PI/3,speed:2.65,radius:.18},keys=Object.create(null),zBuffer=new Float32Array(IW),collected=new Set();
const inventory={flashlight:false,flashlightOn:false,charge:0,batteries:0,almondWater:0,lidar:false};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;ctx.imageSmoothingEnabled=false}addEventListener("resize",resize);resize();
function hashInt(x,y,s=0,l=currentLevel){let h=Math.imul(x|0,374761393)^Math.imul(y|0,668265263)^Math.imul((s+l*131)|0,1442695041);h=Math.imul(h^(h>>>13),1274126177);return(h^(h>>>16))>>>0}function rand(x,y,s=0,l=currentLevel){return hashInt(x,y,s,l)/4294967295}function mod(n,d){return((n%d)+d)%d}function floorDiv(n,d){return Math.floor(n/d)}
function roomCellAt(x,y){const M=12,mx=floorDiv(x,M),my=floorDiv(y,M),lx=mod(x,M),ly=mod(y,M),s=hashInt(mx,my,10);const l=1+s%3,r=9+(s>>>5)%2,t=1+(s>>>9)%3,b=9+(s>>>13)%2;let open=lx>=l&&lx<=r&&ly>=t&&ly<=b;const eo=hashInt(mx,my,20)%100<72,wo=hashInt(mx-1,my,20)%100<72,so=hashInt(mx,my,21)%100<72,no=hashInt(mx,my-1,21)%100<72;const ed=2+hashInt(mx,my,30)%8,wd=2+hashInt(mx-1,my,30)%8,sd=2+hashInt(mx,my,31)%8,nd=2+hashInt(mx,my-1,31)%8;if(eo&&ly>=ed&&ly<=ed+1&&lx>=r)open=true;if(wo&&ly>=wd&&ly<=wd+1&&lx<=l)open=true;if(so&&lx>=sd&&lx<=sd+1&&ly>=b)open=true;if(no&&lx>=nd&&lx<=nd+1&&ly<=t)open=true;if(open){const f=hashInt(mx,my,40)%5;if(f===0&&lx===6&&ly>=t+2&&ly<=b-2&&ly!==6)open=false;if(f===1&&ly===6&&lx>=l+2&&lx<=r-2&&lx!==6)open=false;if(f===2&&(lx===5||lx===8)&&(ly===5||ly===8))open=false}if(Math.abs(x-2)<=4&&Math.abs(y-2)<=4)open=true;return open?0:1}
function caveCellAt(x,y){if(Math.abs(x-2)<=4&&Math.abs(y-2)<=4)return 0;let w=(rand(floorDiv(x,2),floorDiv(y,2),50)*.7+rand(floorDiv(x,5),floorDiv(y,5),51)*.3)<.35;if(mod(x,17)===8||mod(y,19)===9)w=false;return w?1:0}
function suburbCellAt(x,y){if(Math.abs(x-2)<=4&&Math.abs(y-2)<=4)return 0;const bx=mod(x,18),by=mod(y,17);if(bx<=2||by<=2)return 0;const s=hashInt(floorDiv(x,18),floorDiv(y,17),60),i=4+s%2,mx=14-(s>>>4)%2,my=13-(s>>>7)%2,w=bx===i||bx===mx||by===i||by===my;if(!w)return 0;const d=8+(s>>>10)%3;if(by===my&&bx===d)return 0;return 1}
function fieldsCellAt(x,y){if(Math.abs(x-2)<=4&&Math.abs(y-2)<=4)return 0;if(rand(floorDiv(x,4),floorDiv(y,4),70)<.035)return 1;const f=hashInt(floorDiv(x,20),floorDiv(y,20),71)%4;if(f===0&&mod(x,20)===10&&mod(y,7)!==3)return 1;return 0}
function transitionRoomFor(level,x,y){const rs=[];if(level<10)rs.push({cx:16,cy:3,target:level+1});if(level>0)rs.push({cx:-16,cy:3,target:level-1});for(const r of rs)if(x>=r.cx-4&&x<=r.cx+4&&y>=r.cy-4&&y<=r.cy+4){const edge=x===r.cx-4||x===r.cx+4||y===r.cy-4||y===r.cy+4,door=(x===r.cx-4&&y>=r.cy-1&&y<=r.cy+1)||(x===r.cx+4&&y>=r.cy-1&&y<=r.cy+1);return{wall:edge&&!door?1:0,target:r.target}}return null}
function cellAt(x,y){x=Math.floor(x);y=Math.floor(y);const tr=transitionRoomFor(currentLevel,x,y);if(tr)return tr.wall;const t=LEVELS[currentLevel].type;return t==="cave"?caveCellAt(x,y):t==="suburb"?suburbCellAt(x,y):t==="fields"?fieldsCellAt(x,y):roomCellAt(x,y)}
function wallPaletteAt(x,y){const tr=transitionRoomFor(currentLevel,x,y);if(tr){const l=LEVELS[tr.target];return{main:l.wall,side:l.side}}const l=LEVELS[currentLevel];return{main:l.wall,side:l.side}}function isWall(x,y){return cellAt(Math.floor(x),Math.floor(y))===1}function canMoveTo(x,y){const r=player.radius;return!isWall(x-r,y-r)&&!isWall(x+r,y-r)&&!isWall(x-r,y+r)&&!isWall(x+r,y+r)}
function maybeTransition(){if(transitionCooldown>0)return;const x=Math.floor(player.x),y=Math.floor(player.y),tr=transitionRoomFor(currentLevel,x,y);if(!tr||tr.wall)return;const cx=tr.target>currentLevel?16:-16;if(Math.abs(player.x-cx)<1.25&&Math.abs(player.y-3)<1.6){currentLevel=tr.target;player.x=2.5;player.y=2.5;player.angle=0;transitionCooldown=1.25;showTitle()}}
function itemAt(x,y){x=Math.floor(x);y=Math.floor(y);const id=`${currentLevel}:${x}:${y}`;if(collected.has(id)||cellAt(x,y))return null;if(currentLevel===0&&x===6&&y===3)return{id,type:"flashlight",name:"Flashlight"};const r=rand(x,y,90);if(r<.00035)return{id,type:"lidar",name:"LIDAR Scanner"};if(r<.00075)return{id,type:"flashlight",name:"Flashlight"};if(r<.0017)return{id,type:"battery",name:"Battery"};if(r<.00235)return{id,type:"almond",name:"Almond Water"};return null}
function showTitle(){levelTitle.textContent=LEVELS[currentLevel].name;levelTitle.style.opacity="1";titleTimer=2.2}showTitle();
document.addEventListener("keydown",e=>{if(e.code==="KeyF"&&!e.repeat&&inventory.flashlight&&inventory.charge>0)inventory.flashlightOn=!inventory.flashlightOn;if(e.code==="KeyE"&&!e.repeat)collectNearby();keys[e.code]=true});document.addEventListener("keyup",e=>keys[e.code]=false);canvas.addEventListener("click",()=>canvas.requestPointerLock());document.addEventListener("pointerlockchange",()=>lockText.style.display=document.pointerLockElement===canvas?"none":"block");document.addEventListener("mousemove",e=>{if(document.pointerLockElement===canvas)player.angle+=e.movementX*.0025});
function nearbyItem(){const px=Math.floor(player.x),py=Math.floor(player.y);let best=null,bd=999;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const it=itemAt(px+ox,py+oy);if(!it)continue;const d=Math.hypot(px+ox+.5-player.x,py+oy+.5-player.y);if(d<.95&&d<bd){best={...it,x:px+ox,y:py+oy};bd=d}}return best}
function collectNearby(){const it=nearbyItem();if(!it)return;collected.add(it.id);if(it.type==="flashlight"){inventory.flashlight=true;inventory.flashlightOn=true;inventory.charge=Math.max(inventory.charge,100)}else if(it.type==="battery")inventory.batteries++;else if(it.type==="almond")inventory.almondWater++;else if(it.type==="lidar")inventory.lidar=true}
function update(dt){const fx=Math.cos(player.angle),fy=Math.sin(player.angle),rx=Math.cos(player.angle+Math.PI/2),ry=Math.sin(player.angle+Math.PI/2);let dx=0,dy=0;if(keys.KeyW){dx+=fx;dy+=fy}if(keys.KeyS){dx-=fx;dy-=fy}if(keys.KeyA){dx-=rx;dy-=ry}if(keys.KeyD){dx+=rx;dy+=ry}const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len}const step=player.speed*((keys.ShiftLeft||keys.ShiftRight)?1.65:1)*dt,nx=player.x+dx*step,ny=player.y+dy*step;if(canMoveTo(nx,player.y))player.x=nx;if(canMoveTo(player.x,ny))player.y=ny;if(inventory.flashlightOn){inventory.charge-=dt*.75;if(inventory.charge<=0){if(inventory.batteries>0){inventory.batteries--;inventory.charge=100}else{inventory.charge=0;inventory.flashlightOn=false}}}if(titleTimer>0){titleTimer-=dt;if(titleTimer<=0)levelTitle.style.opacity="0"}if(transitionCooldown>0)transitionCooldown-=dt;maybeTransition()}
function castRay(a){const dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(player.x),my=Math.floor(player.y);const ddx=Math.abs(1/(dx||1e-8)),ddy=Math.abs(1/(dy||1e-8));let sx,sy,sdx,sdy;if(dx<0){sx=-1;sdx=(player.x-mx)*ddx}else{sx=1;sdx=(mx+1-player.x)*ddx}if(dy<0){sy=-1;sdy=(player.y-my)*ddy}else{sy=1;sdy=(my+1-player.y)*ddy}let side=0;for(let i=0;i<320;i++){if(sdx<sdy){sdx+=ddx;mx+=sx;side=0}else{sdy+=ddy;my+=sy;side=1}if(cellAt(mx,my))break}const d=side===0?(mx-player.x+(1-sx)/2)/(dx||1e-8):(my-player.y+(1-sy)/2)/(dy||1e-8);let wx=side===0?player.y+d*dy:player.x+d*dx;wx-=Math.floor(wx);return{dist:Math.abs(d),side,wallX:wx,mx,my}}
function shade(b,f){return`rgb(${Math.max(0,Math.min(255,b[0]*f|0))},${Math.max(0,Math.min(255,b[1]*f|0))},${Math.max(0,Math.min(255,b[2]*f|0))})`}
function drawPixelSprite(wx,wy,type){const sp=SPR[type];if(!sp)return;const dx=wx-player.x,dy=wy-player.y,dist=Math.hypot(dx,dy);let a=Math.atan2(dy,dx)-player.angle;while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;if(Math.abs(a)>player.fov*.65||dist<.1)return;const c=dist*Math.cos(a),tot=Math.max(8,Math.floor((IH/c)*.35)),p=Math.max(1,Math.floor(tot/8)),sx=Math.floor(IW/2+(a/(player.fov/2))*(IW/2)),left=sx-p*4,top=Math.floor(IH/2+tot*.14-p*8);for(let sy=0;sy<8;sy++)for(let xx=0;xx<8;xx++){const code=sp[sy][xx];if(code==="0")continue;const px=left+xx*p;if(px<0||px>=IW||c>zBuffer[Math.max(0,Math.min(IW-1,px))])continue;vctx.fillStyle=COL[code];vctx.fillRect(px,top+sy*p,p,p)}}
function renderItems(){const px=Math.floor(player.x),py=Math.floor(player.y);for(let y=py-9;y<=py+9;y++)for(let x=px-9;x<=px+9;x++){const it=itemAt(x,y);if(it)drawPixelSprite(x+.5,y+.5,it.type)}}
function renderWorld(time){const lv=LEVELS[currentLevel],cg=vctx.createLinearGradient(0,0,0,IH/2);cg.addColorStop(0,lv.ceiling[0]);cg.addColorStop(1,lv.ceiling[1]);vctx.fillStyle=cg;vctx.fillRect(0,0,IW,IH/2);const fg=vctx.createLinearGradient(0,IH/2,0,IH);fg.addColorStop(0,lv.floor[0]);fg.addColorStop(1,lv.floor[1]);vctx.fillStyle=fg;vctx.fillRect(0,IH/2,IW,IH/2);if(currentLevel===0||currentLevel===4){const fl=.08+Math.sin(time*.013)*.012;for(let x=10;x<IW;x+=30){vctx.fillStyle=`rgba(255,255,220,${fl})`;vctx.fillRect(x,7,11,2)}}for(let x=0;x<IW;x++){const cam=x/IW-.5,ra=player.angle+cam*player.fov,h=castRay(ra),d=Math.max(.001,h.dist*Math.cos(ra-player.angle));zBuffer[x]=d;const wh=Math.min(IH*3,Math.floor(IH/d)),top=Math.floor((IH-wh)/2),pal=wallPaletteAt(h.mx,h.my),base=h.side===0?pal.main:pal.side;let tex=.92+Math.sin(h.wallX*27)*.035;if(currentLevel===8)tex=.7+rand(h.mx,h.my,170)*.28;if(currentLevel===5)tex=.85+((Math.floor(h.wallX*12)%3)===0?.11:0);let fog=Math.max(.13,Math.min(1,1.5/(d*.20+1)));if(currentLevel===6){const center=Math.abs(x/IW-.5);fog*=inventory.flashlightOn?Math.max(.07,1-center*2.35):.045}else if(inventory.flashlightOn){const center=Math.abs(x/IW-.5);fog*=Math.min(1.25,1.02+Math.max(0,.22-center*.65))}vctx.fillStyle=shade(base,tex*fog);vctx.fillRect(x,top,1,wh)}renderItems();if(currentLevel===6&&!inventory.flashlightOn){vctx.fillStyle="rgba(0,0,0,.93)";vctx.fillRect(0,0,IW,IH)}else if(currentLevel===6&&inventory.flashlightOn){const g=vctx.createRadialGradient(IW/2,IH/2,4,IW/2,IH/2,90);g.addColorStop(0,"rgba(0,0,0,0)");g.addColorStop(.42,"rgba(0,0,0,.24)");g.addColorStop(1,"rgba(0,0,0,.93)");vctx.fillStyle=g;vctx.fillRect(0,0,IW,IH)}}
function renderLidar(){if(!inventory.lidar)return;const radius=5,cs=5,size=(radius*2+1)*cs,ox=14,oy=48;ctx.save();ctx.fillStyle="rgba(4,14,13,.72)";ctx.fillRect(ox-6,oy-18,size+12,size+24);ctx.fillStyle="#79d7c7";ctx.font="10px monospace";ctx.fillText("LIDAR",ox,oy-6);const px=Math.floor(player.x),py=Math.floor(player.y);for(let my=-radius;my<=radius;my++)for(let mx=-radius;mx<=radius;mx++){ctx.fillStyle=cellAt(px+mx,py+my)?"#32524d":"#0f2522";ctx.fillRect(ox+(mx+radius)*cs,oy+(my+radius)*cs,cs-1,cs-1)}const cx=ox+radius*cs+cs/2,cy=oy+radius*cs+cs/2;ctx.fillStyle="#d8fff3";ctx.fillRect(cx-2,cy-2,4,4);ctx.strokeStyle="#d8fff3";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(player.angle)*8,cy+Math.sin(player.angle)*8);ctx.stroke();ctx.restore()}
function updateHUD(){stats.innerHTML=`${LEVELS[currentLevel].name}<br>Flashlight: ${inventory.flashlight?(inventory.flashlightOn?"ON":"OFF"):"yok"}<br>Charge: ${inventory.flashlight?Math.ceil(inventory.charge)+"%":"—"} · Battery: ${inventory.batteries}<br>Almond Water: ${inventory.almondWater}<br>LIDAR: ${inventory.lidar?"ACTIVE":"yok"}`;const it=nearbyItem();if(it){message.style.display="block";message.textContent=`[E] Al: ${it.name}`}else message.style.display="none"}
function render(t){renderWorld(t);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(view,0,0,canvas.width,canvas.height);renderLidar();updateHUD()}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render(now);requestAnimationFrame(loop)}requestAnimationFrame(loop);
