"use strict";

const bootError=document.createElement("pre");
bootError.style.cssText="position:fixed;left:12px;bottom:12px;z-index:99999;max-width:78vw;white-space:pre-wrap;color:#ffb3b3;background:#1b0000;padding:10px;display:none;font:12px monospace";
document.body.appendChild(bootError);

try{
  const sourceUrl=new URL("./game-v13.js",import.meta.url);
  let source=await fetch(sourceUrl).then(r=>{if(!r.ok)throw new Error(`game-v13.js failed to load: ${r.status}`);return r.text()});
  source=source.replace('new URL("./game-v9.js",import.meta.url)','new URL("./src/game-v9.js",location.href)');
  source=source.replace('source=source.replace(\'new URL("./game-v3.js",import.meta.url)\',`new URL("./game-v3.js",${JSON.stringify(import.meta.url)})`);','source=source.replace(\'new URL("./game-v3.js",import.meta.url)\',\'new URL("./src/game-v3.js",location.href)\');');
  source=source.split('await new AsyncFunction(source)();').join('const __rb=new Blob([source],{type:"text/javascript"});const __ru=URL.createObjectURL(__rb);try{await import(__ru)}finally{URL.revokeObjectURL(__ru)}');
  const textPairs=[['sub.textContent="ZORLUK";','sub.textContent="DIFFICULTY";'],['[["easy","KOLAY"],["normal","ORTA"],["hard","ZOR"]]','[["easy","EASY"],["normal","NORMAL"],["hard","HARD"]]'],['"ÖLDÜN"','"YOU DIED"'],['"TEKRAR"','"RESTART"'],['"ELEKTRİK ÇARPMASI"','"ELECTROCUTION"'],['"SANITY TÜKENDİ"','"SANITY DEPLETED"']];
  for(const [a,b] of textPairs)source=source.split(a).join(b);

  const extra=String.raw`
  patched=patched.replace("let selectedSlot=0,boostTimer=0,coffee=0,sanity=100,gameDead=false,maxStamina=0,stamina=0;","let selectedSlot=0,boostTimer=0,coffee=0,sanity=100,gameDead=false,maxStamina=0,stamina=0,lidarNotice='',lidarNoticeTimer=0,monsterLevel=-99,monsters=[];");
  patched=patched.replace("const SC={",`SPRITES.hound=["00011000","00111100","01133110","11333311","01311310","00111100","00100100","01000010"];
SPRITES.smiler=["00000000","00111100","01333310","13333331","13377331","01377310","00111100","00000000"];
SPRITES.faceling=["00011000","00111100","01111110","01100110","01111110","00111100","00100100","01000010"];
const SC={`);
  replaceFn("transitions",`function transitions(l){const a=[];if(l<10){const s=hash(701,911,500,l),ang=(s%24)*Math.PI/12,dist=62+((s>>>5)%29);a.push({cx:Math.round(Math.cos(ang)*dist),cy:Math.round(Math.sin(ang)*dist),target:l+1,main:true})}if(l>0){const s=hash(-877,613,501,l),ang=(s%24)*Math.PI/12+Math.PI/24,dist=66+((s>>>6)%31);a.push({cx:Math.round(Math.cos(ang)*dist),cy:Math.round(Math.sin(ang)*dist),target:l-1,main:true})}for(let gy=-6;gy<=6;gy++)for(let gx=-6;gx<=6;gx++){if(Math.abs(gx)+Math.abs(gy)<3)continue;const h=hash(gx,gy,540,l);if(h%1000>=8)continue;let cx=gx*31+((h>>>8)%15)-7,cy=gy*31+((h>>>12)%15)-7;if(Math.hypot(cx-2.5,cy-2.5)<54)continue;const dir=((h>>>18)%4===0)?-1:1,target=l+dir;if(target<0||target>10)continue;let close=false;for(const q of a)if(Math.hypot(q.cx-cx,q.cy-cy)<24){close=true;break}if(!close)a.push({cx,cy,target,main:false});if(a.length>=7)return a}return a}`);
  replaceFn("drawPlanePattern",`function drawPlanePattern(lv,horizon){const dirX=Math.cos(player.angle),dirY=Math.sin(player.angle),planeScale=Math.tan(player.fov*.5),planeX=-dirY*planeScale,planeY=dirX*planeScale,leftX=dirX-planeX,leftY=dirY-planeY,rightX=dirX+planeX,rightY=dirY+planeY,cache=drawPlanePattern._c||(drawPlanePattern._c=new Map());const rgb=h=>{if(cache.has(h))return cache.get(h);const s=h.slice(1),c=[parseInt(s.slice(0,2),16),parseInt(s.slice(2,4),16),parseInt(s.slice(4,6),16)];cache.set(h,c);return c};for(let y=0;y<H;y++){const delta=Math.abs(y-horizon);if(delta<1)continue;const row=.5*H/delta,stepX=row*(rightX-leftX)/W,stepY=row*(rightY-leftY)/W;let wx=player.x+row*leftX,wy=player.y+row*leftY;const floor=y>horizon;for(let x=0;x<W;x+=2){const ix=Math.floor(wx),iy=Math.floor(wy),fx=wx-ix,fy=wy-iy,tr=trAt(level,ix,iy),sl=tr&&tr.isRoom?LEVELS[tr.target]:lv,t=sl.type;let f=1;if(floor){const macro=.97+.035*Math.sin(wx*.115+wy*.071)+.022*Math.sin(wx*.047-wy*.083);if(t==="yellow")f=macro*(.97+.025*Math.sin(wx*2.35+Math.sin(wy*.63))+.018*Math.sin(wy*4.9)+.012*Math.sin((wx+wy)*8.2))*(rnd(Math.floor(wx/4),Math.floor(wy/4),881)<.07?.93:1);else if(t==="office")f=macro*(.965+.028*Math.sin(wx*3.3)+.021*Math.sin(wy*2.7)+.012*Math.sin((wx-wy)*7.1));else if(t==="hotel"){const ux=((wx%7)+7)%7/7,uy=((wy%7)+7)%7/7,cx=ux-.5,cy=uy-.5,r=Math.hypot(cx,cy),med=.965+(r<.18?.075:0)+(r>.27&&r<.31?.045:0);f=macro*med*(.975+.018*Math.sin(wx*5.8+wy*2.1))}else if(t==="concrete")f=.82+macro*.13+rnd(ix,iy,801)*.06;else if(t==="pipes"||t==="electrical")f=.78+macro*.14+.035*Math.sin(wx*4.2);else if(t==="darkness")f=.52+macro*.08;else if(t==="ocean")f=.75+macro*.16+.035*Math.sin((wx+wy)*2.2);else if(t==="caves")f=.58+macro*.16+rnd(ix,iy,803)*.16;else if(t==="suburb")f=.68+macro*.18;else if(t==="fields")f=.72+macro*.22+.025*Math.sin(wx*1.7+wy*.9)}else{if(t==="yellow"||t==="office"){const seam=fx<.035||fy<.035,fleck=rnd(ix,iy,884)<.08;f=seam?.62:(fleck?.93:1.0)}else if(t==="hotel"){const frame=fx<.035||fy<.035||fx>.965||fy>.965;f=frame?.66:.98+.025*Math.sin((ix+iy)*1.7)}else if(t==="concrete")f=.84+rnd(ix,iy,805)*.10;else if(t==="pipes"||t==="electrical")f=.78+.08*Math.sin(wx*3.1);else if(t==="darkness")f=.48+rnd(ix,iy,806)*.08;else if(t==="ocean")f=.84+.07*Math.sin((wx+wy)*1.9);else if(t==="caves")f=.56+rnd(ix,iy,807)*.22;else if(t==="suburb")f=.80+rnd(ix,iy,808)*.08;else if(t==="fields")f=.96}const c=rgb(floor?sl.floor[0]:sl.ceil[0]);vctx.fillStyle=sh(c,f);vctx.fillRect(x,y,2,1);wx+=stepX*2;wy+=stepY*2}}}`);
  replaceFn("renderWorld",`function renderWorld(time){const lv=LEVELS[level],horizon=H/2+player.pitch*H;vctx.fillStyle=lv.ceil[0];vctx.fillRect(0,0,W,Math.max(0,Math.min(H,horizon)));vctx.fillStyle=lv.floor[0];vctx.fillRect(0,Math.max(0,Math.min(H,horizon)),W,H-Math.max(0,Math.min(H,horizon)));drawPlanePattern(lv,horizon);let exitD=1e9,exitT=null;if(level<10)for(const rr of transitions(level)){if(rr.target!==level+1)continue;const dd=Math.hypot(rr.cx+.5-player.x,rr.cy+.5-player.y);if(dd<exitD){exitD=dd;exitT=rr}}const exitK=exitT&&exitD<60?1-exitD/60:0;if(exitK>0){const ec=LEVELS[exitT.target],hh=Math.max(0,Math.min(H,horizon));vctx.save();vctx.globalAlpha=exitK*.055;vctx.fillStyle=ec.ceil[1]||ec.ceil[0];vctx.fillRect(0,0,W,hh);vctx.globalAlpha=exitK*.10;vctx.fillStyle=ec.floor[1]||ec.floor[0];vctx.fillRect(0,hh,W,H-hh);vctx.restore()}if(level===0||level===4){const f=.08+Math.sin(time*.013)*.012;for(let x=10;x<W;x+=30){vctx.fillStyle="rgba(255,255,220,"+f+")";vctx.fillRect(x,7+player.pitch*H,11,2)}}for(let x=0;x<W;x++){const cam=x/W-.5,a=player.angle+cam*player.fov,hit=cast(a),d=Math.max(.001,hit.dist*Math.cos(a-player.angle));zBuffer[x]=d;const wh=Math.min(H*3,Math.floor(H/d)),top=Math.floor(horizon-wh/2),tr=trAt(level,hit.mx,hit.my),wl=tr&&tr.isRoom?LEVELS[tr.target]:lv,wt=wl.type,base=wallColor(hit.mx,hit.my),wu=(hit.side===0?hit.my:hit.mx)+hit.wallX;let tex=.94;const broad=.975+.035*Math.sin(wu*.31)+.018*Math.sin(wu*.83+hit.mx*.17+hit.my*.11);if(wt==="yellow")tex=broad*(.965+.035*Math.sin(wu*2.15+Math.sin(wu*.47)))*(rnd(hit.mx,hit.my,886)<.08?.91:1);else if(wt==="office")tex=broad*(.98+.025*Math.sin(wu*1.45)+.012*Math.sin(wu*5.7));else if(wt==="hotel")tex=broad*(.91+.065*Math.sin(wu*1.9)+.035*Math.sin(wu*3.8+.8));else if(wt==="concrete")tex=.76+rnd(hit.mx,hit.my,171)*.22;else if(wt==="pipes")tex=.78+.11*Math.sin(wu*3.4)+rnd(hit.mx,hit.my,172)*.08;else if(wt==="electrical")tex=.72+.13*Math.sin(wu*2.8)+rnd(hit.mx,hit.my,173)*.07;else if(wt==="darkness")tex=.45;else if(wt==="ocean")tex=.76+Math.sin(wu*2.4)*.08;else if(wt==="caves")tex=.62+rnd(hit.mx,hit.my,170)*.30;else if(wt==="suburb")tex=.72+.07*Math.sin(wu*1.7);else if(wt==="fields")tex=.82+.06*Math.sin(wu*1.1);let fog=Math.max(.12,Math.min(1,1.5/(d*.20+1)));if(lv.type==="darkness"){const c=Math.abs(x/W-.5);fog*=inv.flashlightOn?Math.max(.07,1-c*2.35):.045}else if(inv.flashlightOn){const c=Math.abs(x/W-.5);fog*=Math.min(1.25,1.02+Math.max(0,.22-c*.65))}vctx.fillStyle=sh(base,tex*fog*(hit.side===0?1:.82)*(1+exitK*.035));vctx.fillRect(x,top,1,wh)}renderStuff();if(lv.type==="darkness"&&!inv.flashlightOn){vctx.fillStyle="rgba(0,0,0,.94)";vctx.fillRect(0,0,W,H)}else if(lv.type==="darkness"&&inv.flashlightOn){const g=vctx.createRadialGradient(W/2,horizon,4,W/2,horizon,90);g.addColorStop(0,"rgba(0,0,0,0)");g.addColorStop(.42,"rgba(0,0,0,.24)");g.addColorStop(1,"rgba(0,0,0,.94)");vctx.fillStyle=g;vctx.fillRect(0,0,W,H)}}`);
  replaceFn("useSelected",`function useSelected(){if(selectedSlot===0){if(inv.flashlight&&inv.charge>0)inv.flashlightOn=!inv.flashlightOn}else if(selectedSlot===1){if(inv.almondWater>0){inv.almondWater--;boostTimer=Math.max(boostTimer,10);sanity=Math.min(100,sanity+35)}}else if(selectedSlot===2){if(inv.lidarLevel>0){let best=null,bd=1e9;for(const r of transitions(level)){const d=Math.hypot(r.cx+.5-player.x,r.cy+.5-player.y);if(d<bd){bd=d;best=r}}lidarNotice=best?("NEAREST EXIT: "+Math.round(bd)+"m  →  LEVEL "+best.target):"NO EXIT SIGNAL";lidarNoticeTimer=4}}else if(selectedSlot===3){if(coffee>0){coffee--;stamina=maxStamina;sanity=Math.min(100,sanity+8)}}}`);
  replaceFn("renderExitHint",`function renderExitHint(){if(level>=10)return;let best=null,bd=1e9;for(const r of transitions(level)){if(r.target!==level+1)continue;const d=Math.hypot(r.cx+.5-player.x,r.cy+.5-player.y);if(d<bd){bd=d;best=r}}const RANGE=64;if(!best||bd>RANGE)return;let rel=Math.atan2(best.cy+.5-player.y,best.cx+.5-player.x)-player.angle;while(rel>Math.PI)rel-=Math.PI*2;while(rel<-Math.PI)rel+=Math.PI*2;const k=1-bd/RANGE,pulse=.78+.22*Math.sin(performance.now()*.008),c=LEVELS[best.target].walls[0],col="rgb("+c[0]+","+c[1]+","+c[2]+")",x=canvas.width/2+Math.max(-.78,Math.min(.78,rel/(player.fov/2)))*canvas.width*.37,y=canvas.height*.75,size=Math.max(26,canvas.height*.035)*(1+k*.65);ctx.save();ctx.globalAlpha=.60+k*.40;ctx.shadowColor=col;ctx.shadowBlur=18+22*k;ctx.fillStyle=col;ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.translate(x,y);ctx.rotate(rel);ctx.beginPath();ctx.moveTo(size,0);ctx.lineTo(-size*.45,-size*.55);ctx.lineTo(-size*.30,-size*.14);ctx.lineTo(-size*.90,-size*.14);ctx.lineTo(-size*.90,size*.14);ctx.lineTo(-size*.30,size*.14);ctx.lineTo(-size*.45,size*.55);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.save();ctx.globalAlpha=.70+k*.30*pulse;ctx.textAlign="center";ctx.font="bold "+Math.max(18,Math.floor(canvas.height*.028))+"px monospace";ctx.shadowColor=col;ctx.shadowBlur=14+20*k;ctx.fillStyle="#fff";ctx.fillText("EXIT NEARBY",canvas.width/2,Math.max(34,canvas.height*.105));ctx.font=Math.max(12,Math.floor(canvas.height*.017))+"px monospace";ctx.fillStyle=col;ctx.fillText(Math.round(bd)+"m",canvas.width/2,Math.max(56,canvas.height*.14));ctx.restore()}`);
  patched=patched.replace("function update(dt){",`const MONSTER_CFG={2:{type:"hound",count:1},3:{type:"hound",count:2},5:{type:"hound",count:1},6:{type:"smiler",count:2},8:{type:"hound",count:2},9:{type:"faceling",count:2}};
function ensureMonsters(){if(monsterLevel===level)return;monsterLevel=level;monsters=[];const cfg=MONSTER_CFG[level];if(!cfg)return;const extra=difficulty==="hard"?1:0;for(let i=0;i<cfg.count+extra;i++){const h=hash(1401+i,1703+i,1600,level),ang=(h%6283)/1000,dist=15+((h>>>8)%15);let bx=Math.round(player.x+Math.cos(ang)*dist),by=Math.round(player.y+Math.sin(ang)*dist),found=null;for(let r=0;r<=6&&!found;r++)for(let yy=-r;yy<=r&&!found;yy++)for(let xx=-r;xx<=r;xx++){if(r&&Math.abs(xx)!==r&&Math.abs(yy)!==r)continue;const x=bx+xx,y=by+yy;if(!cellAt(x,y)&&!trAt(level,x,y)){found={x:x+.5,y:y+.5};break}}if(found)monsters.push({x:found.x,y:found.y,type:cfg.type,phase:(h>>>16)%1000})}}
function updateMonsters(dt){ensureMonsters();const speed=(difficulty==="easy"?1.05:difficulty==="hard"?1.45:1.25);for(const m of monsters){const dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy);if(d<.48){die(m.type==="smiler"?"CAUGHT BY A SMILER":m.type==="faceling"?"CAUGHT BY A FACELESS WANDERER":"CAUGHT BY A HOUND");return}if(d>32||d<.001)continue;const vx=dx/d*speed*dt,vy=dy/d*speed*dt,nx=m.x+vx,ny=m.y+vy;if(!isWall(nx,m.y))m.x=nx;if(!isWall(m.x,ny))m.y=ny}}
function renderMonsters(){ensureMonsters();for(const m of monsters)drawSprite(m.x,m.y,m.type)}
function update(dt){`);
  replaceFn("update",`function update(dt){if(gameDead)return;const fx=Math.cos(player.angle),fy=Math.sin(player.angle),rx=Math.cos(player.angle+Math.PI/2),ry=Math.sin(player.angle+Math.PI/2);let dx=0,dy=0;if(keys.KeyW){dx+=fx;dy+=fy}if(keys.KeyS){dx-=fx;dy-=fy}if(keys.KeyA){dx-=rx;dy-=ry}if(keys.KeyD){dx+=rx;dy+=ry}const L=Math.hypot(dx,dy);if(L){dx/=L;dy/=L}const wantsSprint=(keys.ShiftLeft||keys.ShiftRight)&&L>0;let sprinting=wantsSprint&&stamina>0;if(sprinting){stamina=Math.max(0,stamina-dt*18*DIFF.staminaDrain);if(stamina<=0)sprinting=false}else if(!wantsSprint)stamina=Math.min(maxStamina,stamina+dt*15);const sp=3.45*(sprinting?2.2:1)*(boostTimer>0?1.4:1),stp=sp*dt,nx=player.x+dx*stp,ny=player.y+dy*stp;if(canMove(nx,player.y))player.x=nx;if(canMove(player.x,ny))player.y=ny;if(inv.flashlightOn){inv.charge-=dt*.75;if(inv.charge<=0){if(inv.batteries>0){inv.batteries--;inv.charge=100}else{inv.charge=0;inv.flashlightOn=false}}}sanity=Math.max(0,sanity-dt*.08*DIFF.sanity);if(sanity<=0){die("SANITY DEPLETED");return}if(boostTimer>0)boostTimer=Math.max(0,boostTimer-dt);if(lidarNoticeTimer>0)lidarNoticeTimer=Math.max(0,lidarNoticeTimer-dt);const autoItem=nearItem();if(autoItem&&Math.hypot(autoItem.x+.5-player.x,autoItem.y+.5-player.y)<.40)collect();checkHazards();if(gameDead)return;updateMonsters(dt);if(gameDead)return;if(titleTimer>0){titleTimer-=dt;if(titleTimer<=0)levelTitle.style.opacity="0"}if(transitionCooldown>0)transitionCooldown-=dt;maybeTransition()}`);
  replaceFn("hud",`function hud(){stats.innerHTML=LEVELS[level].name+"<br>Flashlight: "+(inv.flashlight?(inv.flashlightOn?"ON":"OFF"):"none")+" · Charge: "+(inv.flashlight?Math.ceil(inv.charge)+"%":"—")+"<br>Battery: "+inv.batteries+" · Almond: "+inv.almondWater+" · Coffee: "+coffee+" · LIDAR: "+(inv.lidarLevel?"Lv."+inv.lidarLevel:"none")+(boostTimer>0?"<br>Speed boost: "+boostTimer.toFixed(1)+"s":"")+(lidarNoticeTimer>0?"<br><b>"+lidarNotice+"</b>":"");const it=nearItem();if(it){message.style.display="block";message.textContent="[E] Pick up: "+it.name}else message.style.display="none"}`);
  replaceFn("render",`function render(t){renderWorld(t);renderMonsters();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(view,0,0,canvas.width,canvas.height);renderExitHint();renderLidar();renderSanity();renderStamina();renderHotbar();renderSanityFX();hud()}`);
`;
  const marker='}\n\nconst sourceUrl=new URL("./game-v9.js",import.meta.url);';
  if(!source.includes(marker))throw new Error("v16 patch insertion marker not found");
  source=source.replace(marker,extra+'\n'+marker);
  const blob=new Blob([source],{type:"text/javascript"});
  const blobUrl=URL.createObjectURL(blob);
  try{await import(blobUrl)}finally{URL.revokeObjectURL(blobUrl)}
}catch(err){bootError.style.display="block";bootError.textContent="Backrooms v16 bootstrap failed.\n"+(err?.stack||err?.message||String(err));console.error(err)}